title: Gregory Prestegord Art
# email: 
description: >-
  Gregory Prestegord is an artist and a keeper of birds.
baseurl: "greg-prestegord-art"
# url: ""
# google_analytics: ""

markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  pages:
    output: true
    permalink: /:title
  paintings:
    output: true
    permalink: /painting/:name

defaults:
  - scope:
      path: ""
      type: paintings
    values:
      layout: painting

plugins:
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-hostname
  - jekyll-hashsert

jekyll-minifier:
  exclude:
    - "sitemap.xml"
    - "assets/css/theme.css"


extlinks:
  attributes: { rel: nofollow noopener noreferrer, target: _blank }
#  rel_include: [ "l.gourav.sh" ]
#  rel_exclude: [ "gourav.sh", "github.com", "genicsblog.com" ]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
